# /etc/ood/config/ondemand.d/ondemand.yml

pinned_apps_menu_length: 8        # the default number of items in the dropdown menu list

dashboard_layout:
  rows:
    - columns:
      - width: 12
        widgets:
          - pinned_apps
          - motd
#          - xdmod_widget_job_efficiency
#          - xdmod_widget_jobs
    - columns:
      - width: 6
        widgets: ['xdmod_widget_job_efficiency']
      - width: 6
        widgets: ['xdmod_widget_jobs']

pinned_apps:
  - sys/chpc-systemstatus
  - sys/desktop_basic
  - sys/desktop_expert
  - sys/jupyter_app
  - sys/rstudio_server_app
  - sys/matlab_app
  - sys/comsol_app
  - sys/codeserver_app
  - sys/vmd_app
  - sys/ansys_workbench_app
  - sys/abaqus_app
  - sys/idl_app

# pinned_apps_group_by: category    # defaults to nil, no grouping
