---
title: "Interactive Desktop"
description: |
  This app will launch an interactive linux desktop on a **single compute node**, or a Frisco node.

  This is meant for all types of tasks such as:

  - accessing & viewing files
  - compiling code
  - debugging
  - running visualization software **without** 3D hardware acceleration

submit: "submit/slurm.yml.erb"

#form:
#  - bc_vnc_idle
#  - desktop
#  - bc_num_hours
#  - bc_num_slots
#  - num_cores
#  - node_type
#  - bc_account
#  - bc_queue
#  - bc_vnc_resolution
#  - bc_email_on_started
#  - slurm_cluster

