---
v2:
  metadata:
    title: "Notchpeak"
    priority: 2
  login:
    host: "notchpeak.chpc.utah.edu"
  job:
    adapter: "slurm"
    cluster: "notchpeak"
    bin: "/uufs/notchpeak.peaks/sys/installdir/slurm/std/bin"
  custom:
    xdmod:
      resource_id: 28
    queues:
      - "notchpeak"
      - "notchpeak-guest"
      - "notchpeak-freecycle"
  batch_connect:
    basic:
      script_wrapper: |
        if [ -z "$LMOD_VERSION" ]; then
           source /etc/profile.d/chpc.sh
        fi
        env
        export XDG_RUNTIME_DIR=$(mktemp -d)
        # reset SLURM_EXPORT_ENV so that things like srun & sbatch have the same environment as the host
        export SLURM_EXPORT_ENV=ALL
        %s
      set_host: "host=$(/uufs/chpc.utah.edu/sys/bin/hostfromroute.sh ondemand.chpc.utah.edu)"
    vnc:
      script_wrapper: |
        if [ -z "$LMOD_VERSION" ]; then
           source /etc/profile.d/chpc.sh
        fi
        env
        export PATH="/uufs/chpc.utah.edu/sys/installdir/turbovnc/std/opt/TurboVNC/bin:$PATH"
        export WEBSOCKIFY_CMD="/uufs/chpc.utah.edu/sys/installdir/websockify/0.8.0/bin/websockify"
        export XDG_RUNTIME_DIR=$(mktemp -d)
        # reset SLURM_EXPORT_ENV so that things like srun & sbatch have the same environment as the host
        export SLURM_EXPORT_ENV=ALL
        %s
      set_host: "host=$(/uufs/chpc.utah.edu/sys/bin/hostfromroute.sh ondemand.chpc.utah.edu)"

#      set_host: "host=$(hostname -A | awk '{print $2}')"
# first hostname - TCP, second hostname - IB

