---
v2:
  metadata:
    title: "Tangent"
    priority: 5
  login:
    host: "tangent.chpc.utah.edu"
  job:
    adapter: "slurm"
    cluster: "tangent"
    bin: "/uufs/tangent.peaks/sys/pkg/slurm/std/bin"
  custom:
    xdmod:
      resource_id: 33
  batch_connect:
    basic:
      script_wrapper: |
        if [ -z "$LMOD_VERSION" ]; then
           source /etc/profile.d/chpc.sh
        fi
        export XDG_RUNTIME_DIR=$(mktemp -d)
        %s
      set_host: "host=$(/uufs/chpc.utah.edu/sys/bin/hostfromroute.sh ondemand.chpc.utah.edu)"
    vnc:
      script_wrapper: |
        if [ -z "$LMOD_VERSION" ]; then
           source /etc/profile.d/chpc.sh
        fi
        export PATH="/uufs/chpc.utah.edu/sys/installdir/turbovnc/std/opt/TurboVNC/bin:$PATH"
        export WEBSOCKIFY_CMD="/uufs/chpc.utah.edu/sys/installdir/websockify/0.8.0/bin/websockify"
        export XDG_RUNTIME_DIR=$(mktemp -d)
        %s
      set_host: "host=$(/uufs/chpc.utah.edu/sys/bin/hostfromroute.sh ondemand.chpc.utah.edu)"

